<?php


/**
 * Implements hook_form_FORM_ID_alter().
 */
function dblog_search_form_dblog_filter_form_alter(&$form, &$form_state, $form_id) {
  $search_field = array(
    'search' => array(
      '#title' => t('Message'),
      '#type' => 'textfield',
      '#default_value' => '',
    ),
  );
  $form['filters'] = $search_field + $form['filters'];

  if (!empty($_SESSION['dblog_overview_search'])) {
    $form['filters']['search']['#default_value'] = $_SESSION['dblog_overview_search'];
  }

  $form['#validate'] = array('dblog_search_filter_form_validate');
  $form['#submit'][] = 'dblog_search_filter_form_submit';
}


/**
 * Additional form validation handler for dblog_filter_form().
 */
function dblog_search_filter_form_validate($form, &$form_state) {
  if ($form_state['values']['op'] == t('Filter') && empty($form_state['values']['type']) &&
      empty($form_state['values']['severity']) && empty($form_state['values']['search'])) {
    form_set_error('type', t('You must select something to filter by.'));
  }
}


/**
 * Additional form submission handler for dblog_filter_form().
 */
function dblog_search_filter_form_submit($form, &$form_state) {
  $op = $form_state['values']['op'];
  switch ($op) {
    case t('Filter'):
      if (isset($form_state['values']['search'])) {
        $_SESSION['dblog_overview_search'] = $form_state['values']['search'];
      }
      break;
    case t('Reset'):
      $_SESSION['dblog_overview_search'] = array();
      break;
  }
  return 'admin/reports/dblog';
}


/**
 * Implementation of hook_menu_alter().
 */
function dblog_search_menu_alter(&$items) {
  $items['admin/reports/dblog']['page callback'] = 'dblog_search_overview';
}


/**
 * Page callback: Displays a listing of database log messages, allowing to
 * search in message and variables.
 */
function dblog_search_overview() {
  if (empty($_SESSION['dblog_overview_search'])) {
    return dblog_overview();
  }

  // dblog search
  $filter = dblog_search_build_filter_query();

  $rows = array();
  $classes = array(
    WATCHDOG_DEBUG     => 'dblog-debug',
    WATCHDOG_INFO      => 'dblog-info',
    WATCHDOG_NOTICE    => 'dblog-notice',
    WATCHDOG_WARNING   => 'dblog-warning',
    WATCHDOG_ERROR     => 'dblog-error',
    WATCHDOG_CRITICAL  => 'dblog-critical',
    WATCHDOG_ALERT     => 'dblog-alert',
    WATCHDOG_EMERGENCY => 'dblog-emerg',
  );

  $build['dblog_filter_form'] = drupal_get_form('dblog_filter_form');
  $build['dblog_clear_log_form'] = drupal_get_form('dblog_clear_log_form');

  $header = array(
    '', // Icon column.
    array('data' => t('Type'), 'field' => 'w.type'),
    array('data' => t('Date'), 'field' => 'w.wid', 'sort' => 'desc'),
    t('Message'),
    array('data' => t('User'), 'field' => 'u.name'),
    array('data' => t('Operations')),
  );

  $query = db_select('watchdog', 'w')->extend('PagerDefault')->extend('TableSort');
  $query->leftJoin('users', 'u', 'w.uid = u.uid');
  $query
    ->fields('w', array('wid', 'uid', 'severity', 'type', 'timestamp', 'message', 'variables', 'link'))
    ->addField('u', 'name');
  if (!empty($filter['where'])) {
    $query->where($filter['where'], $filter['args']);
  }
  $result = $query
    ->limit(50)
    ->orderByHeader($header)
    ->execute();

  foreach ($result as $dblog) {
    $rows[] = array('data' =>
      array(
        // Cells
        array('class' => 'icon'),
        t($dblog->type),
        format_date($dblog->timestamp, 'short'),
        theme('dblog_message', array('event' => $dblog, 'link' => TRUE)),
        theme('username', array('account' => $dblog)),
        filter_xss($dblog->link),
      ),
      // Attributes for tr
      'class' => array(drupal_html_class('dblog-' . $dblog->type), $classes[$dblog->severity]),
    );
  }

  $build['dblog_table'] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
    '#attributes' => array('id' => 'admin-dblog'),
    '#empty' => t('No log messages available.'),
  );
  $build['dblog_pager'] = array('#theme' => 'pager');

  return $build;
}


/**
 * dblog_build_filter_query() modified to match search text against description & variables columns.
 */
function dblog_search_build_filter_query() {
  if (empty($_SESSION['dblog_overview_filter']) && empty($_SESSION['dblog_overview_search'])) {
    return;
  }

  $filters = dblog_filters();
  
  // Build query
  $where = $args = array();
  foreach ($_SESSION['dblog_overview_filter'] as $key => $filter) {
    $filter_where = array();
    foreach ($filter as $value) {
      $filter_where[] = $filters[$key]['where'];
      $args[] = $value;
    }
    if (!empty($filter_where)) {
      $where[] = '(' . implode(' OR ', $filter_where) . ')';
    }
  }
  
  // Add description & variable search to query
  if (!empty($_SESSION['dblog_overview_search'])) {
    $where[] = '(w.message LIKE ?) OR (w.variables LIKE ?)';
    $args[] = '%' . $_SESSION['dblog_overview_search'] . '%';
    $args[] = '%' . $_SESSION['dblog_overview_search'] . '%';
  }
  
  $where = !empty($where) ? implode(' AND ', $where) : '';

  return array(
    'where' => $where,
    'args' => $args,
  );
}
